In [1]:
# Area, bedrooms, age are called independent variables or feature whereas price is the dependent variable. 
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
#read the data from the CSV file
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
# Data preprocessing: Fill NA values with median value of a column
import math
med_bedrooms = math.floor(df.bedrooms.median())

In [6]:
#fill the NaN data with median values
df.bedrooms = df.bedrooms.fillna(med_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
#buiding the model and fit the model
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
#find the coefficiant
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [10]:
#find the intercept
reg.intercept_

221323.00186540425

In [11]:
#find the home price with 3000 sqr ft area, 3 bedrooms and 40 year old
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [12]:
#find the home price with 3000 sqr ft area, 3 bedrooms and 40 year old
(112.06244194*3000) + (23388.88007794*3) + (-3231.71790863*40) + 221323.00186540425

498408.25157402427

In [13]:
#find the home price with 2500 sqr ft area, 4 bedrooms and  5 years old
reg.predict([[2500, 4, 5]])


array([578876.03748933])