In [1]:
#importing module
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
#creating and fitting the mode
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [4]:
#printing coefficiant m 
model.coef_

array([135.78767123])

In [5]:
#printing the intercept b 
model.intercept_

180616.43835616432

In [7]:
#prediction price for the 5000 square feet. 
model.predict(5000)

array([859554.79452055])

In [9]:
# importing pickle
import pickle

In [13]:
#save the model to a file using python pickle
with open('model_pickle', 'wb') as file:
    pickle.dump(model, file)

In [16]:
#read the model from the file. 
with open('model_pickle', 'rb') as file:
    mp = pickle.load(file)

In [18]:
#printing coefficiant m
mp.coef_

array([135.78767123])

In [19]:
#printing intercept b
mp.intercept_

180616.43835616432

In [20]:
#predicting the price for the 5000 square feet house
mp.predict(5000)

array([859554.79452055])

In [21]:
 #save trained model using joblib
from sklearn.externals import joblib

In [22]:
# Saving the model into the file. 
joblib.dump(model, 'model_joblib')

['model_joblib']

In [23]:
#loading the model
mj = joblib.load('model_joblib')

In [24]:
#print the coefficiant
mj.coef_

array([135.78767123])

In [25]:
#print the model 
mj.intercept_

180616.43835616432

In [26]:
#predicting the price for the 5000 square feet house. 
mj.predict(5000)

array([859554.79452055])