In [1]:
#importing module
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
#reading the csv file
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
#creating and fitting the model
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [4]:
#printing coefficiant m
model.coef_

array([ 135.78767123])

In [5]:
#printing the intercept b
model.intercept_

180616.43835616432

In [6]:
#predicting the price for 5000 square feet
model.predict(5000)

array([ 859554.79452055])

In [8]:
#importing pickle
import pickle 

In [9]:
#save the model to a file using pythong pickle 
with open('model_pickleA', 'wb') as file:
    pickle.dump(model, file)

In [12]:
#read the model from the file
with open('model_pickleA', 'rb') as file:
    mp = pickle.load(file)

In [13]:
#printing the coefficiant m
mp.coef_

array([ 135.78767123])

In [14]:
#printing the intercept or slop b
mp.intercept_

180616.43835616432

In [15]:
#printing the price for 5000 squre feet house
mp.predict(5000)

array([ 859554.79452055])

In [16]:
# importing the modul for joblib
from sklearn.externals import joblib

In [17]:
# save trained model using joblib
joblib.dump(model, 'model_joblibA')

['model_joblibA']

In [18]:
#loading the model
mj = joblib.load('model_joblibA')

In [19]:
#printing the coefficiant
mj.coef_

array([ 135.78767123])

In [20]:
#printing the model 
mj.intercept_

180616.43835616432

In [21]:
#printing the price for the 5000 square feet house
mj.predict(5000)

array([ 859554.79452055])